[package]
name = "worker"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
apalis = { version = "0.7.4", features = ["limit"] }
apalis-redis = "0.7.4"
aws-creds = "0.39.1"
csv = "1.4.0"
rust-s3 = "0.37.2"
serde = "1.0.228"
serde_json = "1.0.150"
tokio = { version = "1.52.2", features = ["macros", "rt-multi-thread", "signal"] }
uuid = { version = "1.23.1", features = ["v4"] }
