erDiagram
    User {
        UUID id
        string email
        string hash_password
    }
    User }o--o{ Group : belongs-to
    Group {
        UUID id
        string name
    }

    Datasource {
        UUID id
        UUID S3ID
        string name
        ENUM type
        float size
        date created_at
    }
    Datasource ||--|| UUID-CSV-DT-1 : references-CSV
    UUID-CSV-DT-1{
        int value1
        string value2
        bool value3
    }
    Datasource ||--|| UUID-CSV-DT-2 : references-CSV
    UUID-CSV-DT-2{
    }
    JSONTable{
        JSONB document
    }
    JSONTable ||--|o Datasource : references-JSON
    Datasource ||--o{ Group : property-of

    Job {
        UUID id
        string name
        ENUM[] actions
        ENUM status

    }
    Job ||--o{ Datasource : related-to
